# Generated by Django 3.2.5 on 2021-08-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_addworkspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addworkspace',
            old_name='name',
            new_name='spacename',
        ),
    ]
